### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by maoueh** [getsetgames/guava-light#1]
Did you release this to some repository yet? I would be delighted to use this in my own application.

I was looking to do this since a long time ago. Thanks for putting this together!

**Comment by robertfsegal** [comment]
Hey @maoueh you are welcome to pull the repository as is and integrate it into your project.    Are there any roadblocks to doing this?

**Comment by maoueh** [comment]
Yeah could do that of course, I was just wondering if it was pushed/released to a central repository like maven central or the like to be a little bit easier :)

Think this answers my question. Thank you for putting this together.

**Comment by robertfsegal** [comment]
ah yeah sorry I haven't done a huge amount of work with this just enough for my purposes.
